In [1]:
import pandas as pd
import numpy as np

In [2]:
X_train = pd.read_csv('training_set_features.csv')
y_train = pd.read_csv('training_set_labels.csv').xyz_vaccine
X_test = pd.read_csv('test_set_features.csv')

In [3]:
# list = ['age_group','education','race','sex','income_poverty','marital_status','rent_or_own','employment_status','hhs_geo_region','census_msa',
#        'employment_industry','employment_occupation']

In [4]:
X_train.head(3)

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0   
1              1          3.0            2.0                        0.0   
2              2          1.0            1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
2                   1.0                   0.0                    0.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
2                          0.0                      0.0   

   behavioral_touch_face  ...             income_poverty  marital_status  \
0                    1.0  ...              Below Poverty     Not Married   
1                    1.0  ...              Below Poverty     Not Married   
2                    0.0  ...  <= $75,000, Above Poverty     Not Married   

   rent_or_own   employment_status  hhs_geo_region                census_msa  \
0          Own  Not in Labor Force        oxchjgsf                   Non-MSA   
1         Rent            Employed        bhuqouqj  MSA, Not Principle  City   
2          Own            Employed        qufhixun  MSA, Not Principle  City   

   household_adults  household_children  employment_industry  \
0               0.0                 0.0                  NaN   
1               0.0                 0.0             pxcmvdjn   
2               2.0                 0.0             rucpziij   

   employment_occupation  
0                    NaN  
1               xgwztkwe  
2               xtkaffoo  

[3 rows x 36 columns]

In [5]:
X_train.dtypes

respondent_id                    int64
xyz_concern                    float64
xyz_knowledge                  float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_xyz                float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_xyz_vacc_effective     float64
opinion_xyz_risk               float64
opinion_xyz_sick_from_vacc     float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                       object
education                       object
race                            object
sex                      

In [6]:
for col in X_train.select_dtypes('object').columns:
    X_train[col] = X_train[col].astype('category')

In [7]:
X_train.dtypes

respondent_id                     int64
xyz_concern                     float64
xyz_knowledge                   float64
behavioral_antiviral_meds       float64
behavioral_avoidance            float64
behavioral_face_mask            float64
behavioral_wash_hands           float64
behavioral_large_gatherings     float64
behavioral_outside_home         float64
behavioral_touch_face           float64
doctor_recc_xyz                 float64
doctor_recc_seasonal            float64
chronic_med_condition           float64
child_under_6_months            float64
health_worker                   float64
health_insurance                float64
opinion_xyz_vacc_effective      float64
opinion_xyz_risk                float64
opinion_xyz_sick_from_vacc      float64
opinion_seas_vacc_effective     float64
opinion_seas_risk               float64
opinion_seas_sick_from_vacc     float64
age_group                      category
education                      category
race                           category


In [8]:
X_train.isnull().sum()

respondent_id                      0
xyz_concern                       92
xyz_knowledge                    116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_xyz_vacc_effective       391
opinion_xyz_risk                 388
opinion_xyz_sick_from_vacc       395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
m

In [9]:
X_train.drop(['health_insurance','employment_industry','employment_occupation'],axis=1,inplace=True)

In [10]:
X_train.dropna(axis=0,inplace=True)

In [11]:
# Get the index of the remaining rows after dropping NA
remaining_index = X_train.index

# Use this index to filter 'y_train'
y_train = y_train.loc[remaining_index]


In [12]:
category_column=['age_group', 'education', 'race', 'sex', 'income_poverty',
       'marital_status', 'rent_or_own', 'employment_status', 'hhs_geo_region',
       'census_msa']

In [13]:
X_train=pd.get_dummies(X_train, columns=category_column)

In [14]:
X_train.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0   
1              1          3.0            2.0                        0.0   
3              3          1.0            1.0                        0.0   
4              4          2.0            1.0                        0.0   
5              5          3.0            1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
3                   1.0                   0.0                    1.0   
4                   1.0                   0.0                    1.0   
5                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
3                          1.0                      0.0   
4                          1.0                      0.0   
5                          0.0                      0.0   

   behavioral_touch_face  ...  hhs_geo_region_fpwskwrf  \
0                    1.0  ...                    False   
1                    1.0  ...                    False   
3                    0.0  ...                    False   
4                    1.0  ...                    False   
5                    1.0  ...                    False   

   hhs_geo_region_kbazzjca  hhs_geo_region_lrircsnp  hhs_geo_region_lzgpxyit  \
0                    False                    False                    False   
1                    False                    False                    False   
3                    False                     True                    False   
4                    False                    False                    False   
5                    False                    False                    False   

   hhs_geo_region_mlyzmhmf  hhs_geo_region_oxchjgsf  hhs_geo_region_qufhixun  \
0                    False                     True                    False   
1                    False                    False                    False   
3                    False                    False                    False   
4                    False                    False                     True   
5                    False                    False                    False   

   census_msa_MSA, Not Principle  City  census_msa_MSA, Principle City  \
0                                False                           False   
1                                 True                           False   
3                                False                            True   
4                                 True                           False   
5                                False                            True   

   census_msa_Non-MSA  
0                True  
1               False  
3               False  
4               False  
5               False  

[5 rows x 61 columns]

In [15]:
# model = SVC(probability=True)
# model.fit(X_train, y_train)

In [16]:
# probabilities = model.predict_proba(X)

In [17]:
X_test.isnull().sum()

respondent_id                      0
xyz_concern                       85
xyz_knowledge                    122
behavioral_antiviral_meds         79
behavioral_avoidance             213
behavioral_face_mask              19
behavioral_wash_hands             40
behavioral_large_gatherings       72
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            932
child_under_6_months             813
health_worker                    789
health_insurance               12228
opinion_xyz_vacc_effective       398
opinion_xyz_risk                 380
opinion_xyz_sick_from_vacc       375
opinion_seas_vacc_effective      452
opinion_seas_risk                499
opinion_seas_sick_from_vacc      521
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4497
m

In [18]:
for col in X_test.select_dtypes('object').columns:
    X_test[col] = X_test[col].astype('category')

In [19]:
X_test.drop(['health_insurance','employment_industry','employment_occupation'],axis=1,inplace=True)

In [20]:
X_test.dropna(axis=0,inplace=True)

In [53]:
remaining_index1 = X_test.index

In [59]:
X_test.shape

(19592, 61)

In [21]:
category_column=['age_group', 'education', 'race', 'sex', 'income_poverty',
       'marital_status', 'rent_or_own', 'employment_status', 'hhs_geo_region',
       'census_msa']

In [22]:
X_test=pd.get_dummies(X_test, columns=category_column)

In [23]:
from sklearn.svm import SVC
model = SVC(probability=True)
model.fit(X_train, y_train)

SVC(probability=True)

In [24]:
probabilities = model.predict_proba(X_test)

In [26]:
probabilities.shape

(19592, 2)

In [27]:
positive_class_probabilities = probabilities[:, 1]
positive_class_probabilities

array([0.2267058 , 0.22656135, 0.22718008, ..., 0.01751881, 0.01752282,
       0.01752602])

In [28]:
positive_class_probabilities[200:278]

array([0.22072627, 0.22018681, 0.22032532, 0.22080078, 0.22044313,
       0.22040778, 0.22014472, 0.22073918, 0.22101067, 0.22016001,
       0.22028402, 0.22011349, 0.22026103, 0.22018907, 0.22045105,
       0.22011545, 0.21990654, 0.22011745, 0.22053869, 0.22002077,
       0.22090993, 0.22005809, 0.22014763, 0.22009732, 0.2201615 ,
       0.22002065, 0.21962858, 0.22018792, 0.21980774, 0.22012322,
       0.21989148, 0.21987369, 0.21975022, 0.22010603, 0.21943036,
       0.22013495, 0.21980915, 0.21946816, 0.21961054, 0.2197546 ,
       0.21899813, 0.21963187, 0.21932041, 0.21949269, 0.21955634,
       0.21914549, 0.21931719, 0.21886433, 0.21885811, 0.21894892,
       0.21907596, 0.2191315 , 0.21897612, 0.21891415, 0.2193062 ,
       0.21969658, 0.21917298, 0.21870829, 0.2188696 , 0.21862414,
       0.21871618, 0.21942757, 0.21921118, 0.21847064, 0.21886409,
       0.21904005, 0.21855908, 0.21838235, 0.21871093, 0.21846066,
       0.2191129 , 0.2183062 , 0.21872531, 0.21861923, 0.21868

In [29]:
y_train1 = pd.read_csv('training_set_labels.csv').seasonal_vaccine

In [30]:
X_train.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0   
1              1          3.0            2.0                        0.0   
3              3          1.0            1.0                        0.0   
4              4          2.0            1.0                        0.0   
5              5          3.0            1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
3                   1.0                   0.0                    1.0   
4                   1.0                   0.0                    1.0   
5                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
3                          1.0                      0.0   
4                          1.0                      0.0   
5                          0.0                      0.0   

   behavioral_touch_face  ...  hhs_geo_region_fpwskwrf  \
0                    1.0  ...                    False   
1                    1.0  ...                    False   
3                    0.0  ...                    False   
4                    1.0  ...                    False   
5                    1.0  ...                    False   

   hhs_geo_region_kbazzjca  hhs_geo_region_lrircsnp  hhs_geo_region_lzgpxyit  \
0                    False                    False                    False   
1                    False                    False                    False   
3                    False                     True                    False   
4                    False                    False                    False   
5                    False                    False                    False   

   hhs_geo_region_mlyzmhmf  hhs_geo_region_oxchjgsf  hhs_geo_region_qufhixun  \
0                    False                     True                    False   
1                    False                    False                    False   
3                    False                    False                    False   
4                    False                    False                     True   
5                    False                    False                    False   

   census_msa_MSA, Not Principle  City  census_msa_MSA, Principle City  \
0                                False                           False   
1                                 True                           False   
3                                False                            True   
4                                 True                           False   
5                                False                            True   

   census_msa_Non-MSA  
0                True  
1               False  
3               False  
4               False  
5               False  

[5 rows x 61 columns]

In [31]:
y_train1 = y_train1.loc[remaining_index]

In [32]:
y_train1.shape

(19642,)

In [33]:
model.fit(X_train,y_train1)

SVC(probability=True)

In [38]:
probabilities1 = model.predict_proba(X_test)

In [39]:
probabilities1

array([[6.43268621e-01, 3.56731379e-01],
       [6.82799992e-01, 3.17200008e-01],
       [5.54546213e-01, 4.45453787e-01],
       ...,
       [9.99928783e-01, 7.12173086e-05],
       [9.99928660e-01, 7.13403382e-05],
       [9.99928583e-01, 7.14166681e-05]])

In [40]:
positive_class_probabilities1 = probabilities1[:, 1]
positive_class_probabilities1

array([3.56731379e-01, 3.17200008e-01, 4.45453787e-01, ...,
       7.12173086e-05, 7.13403382e-05, 7.14166681e-05])

In [41]:
remaining_index

Index([    0,     1,     3,     4,     5,     6,     7,     8,     9,    10,
       ...
       26693, 26694, 26697, 26698, 26699, 26700, 26701, 26702, 26703, 26706],
      dtype='int64', length=19642)

In [61]:
final_answer = pd.DataFrame({
    'respondent_id':remaining_index1,
    'h1n1_vaccine':positive_class_probabilities,
    'seasonal_vaccine':positive_class_probabilities1
})

In [62]:
final_answer.head()

respondent_id  h1n1_vaccine  seasonal_vaccine
0              0      0.226706          0.356731
1              1      0.226561          0.317200
2              2      0.227180          0.445454
3              3      0.226995          0.420912
4              4      0.226736          0.417761

In [66]:
final_answer.to_csv('prediction.csv',index=False)